name: Test JMeter Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run JMeter Action
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: upload jmeter artifacts
        uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
